// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL0BrA0exRCVevpjsyjchJLFFMpG5V-h8',
    appId: '1:32238085676:web:2c88367b9491c36d6c1389',
    messagingSenderId: '32238085676',
    projectId: 'habier-1e0e6',
    authDomain: 'habier-1e0e6.firebaseapp.com',
    storageBucket: 'habier-1e0e6.firebasestorage.app',
    measurementId: 'G-S8RE33TDS5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOMZTbvwEmp3vaEQTfaPXw87IYBrPsD78',
    appId: '1:32238085676:android:1a41d85d054d7d0b6c1389',
    messagingSenderId: '32238085676',
    projectId: 'habier-1e0e6',
    storageBucket: 'habier-1e0e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa4XUnciYGq-3_rEI4htrIhN1oeHqM4rM',
    appId: '1:32238085676:ios:e506c4a36b80ac5b6c1389',
    messagingSenderId: '32238085676',
    projectId: 'habier-1e0e6',
    storageBucket: 'habier-1e0e6.firebasestorage.app',
    iosBundleId: 'com.example.habier',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAa4XUnciYGq-3_rEI4htrIhN1oeHqM4rM',
    appId: '1:32238085676:ios:e506c4a36b80ac5b6c1389',
    messagingSenderId: '32238085676',
    projectId: 'habier-1e0e6',
    storageBucket: 'habier-1e0e6.firebasestorage.app',
    iosBundleId: 'com.example.habier',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAL0BrA0exRCVevpjsyjchJLFFMpG5V-h8',
    appId: '1:32238085676:web:d1c1edf1df2872a36c1389',
    messagingSenderId: '32238085676',
    projectId: 'habier-1e0e6',
    authDomain: 'habier-1e0e6.firebaseapp.com',
    storageBucket: 'habier-1e0e6.firebasestorage.app',
    measurementId: 'G-9PEEKQPYQ2',
  );
}
